"""
Deterministic patch application for invoice state.
This handles the mechanical execution of patches generated by the LLM.
"""

from typing import Dict, Any
import copy


def apply_patch_deterministic(state: Dict[str, Any], patch: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply a patch to the state using deterministic Python code.
    
    The patch is generated by LLM (agentic), but applied deterministically for reliability.
    """
    if not patch:
        return state
    
    # Deep copy to avoid mutating original
    result = copy.deepcopy(state)
    
    # Sort deletion patches by index (highest to lowest) to avoid index shifting
    deletion_patches = []
    other_patches = []
    
    for key, value in patch.items():
        if value == "__DELETE__":
            deletion_patches.append((key, value))
        else:
            other_patches.append((key, value))
    
    # Sort deletions by extracting index and sorting in reverse
    def extract_index(key_str):
        """Extract array index from key like 'freight_bill.runs[21]'"""
        import re
        match = re.search(r'\[(-?\d+)\]', key_str)
        if match:
            return int(match.group(1))
        return -999  # Non-array keys go first
    
    deletion_patches.sort(key=lambda x: extract_index(x[0]), reverse=True)
    
    # Apply deletions first (from highest index to lowest)
    for key, value in deletion_patches:
        _apply_single_patch(result, key, value)
        print(f"✓ Applied patch: {key}")
    
    # Apply other patches
    for key, value in other_patches:
        _apply_single_patch(result, key, value)
        print(f"✓ Applied patch: {key}")
    
    return result


def _apply_single_patch(state: Dict[str, Any], key: str, value: Any) -> None:
    """
    Apply a single patch operation to the state (in-place).
    
    Supports:
    - Nested paths: "freight_bill.to_party.name"
    - Array indices: "freight_bill.runs[5].rate"
    - Negative indices: "freight_bill.runs[-1]"
    - Deletions: value = "__DELETE__"
    """
    import re
    
    # Parse the key to extract path components
    parts = []
    current = ""
    i = 0
    
    while i < len(key):
        if key[i] == '.':
            if current:
                parts.append(('field', current))
                current = ""
            i += 1
        elif key[i] == '[':
            if current:
                parts.append(('field', current))
                current = ""
            # Find matching ]
            j = i + 1
            while j < len(key) and key[j] != ']':
                j += 1
            index_str = key[i+1:j]
            parts.append(('index', int(index_str)))
            i = j + 1
        else:
            current += key[i]
            i += 1
    
    if current:
        parts.append(('field', current))
    
    # Navigate to the parent of the target
    current_obj = state
    for i, (part_type, part_value) in enumerate(parts[:-1]):
        if part_type == 'field':
            if part_value not in current_obj:
                current_obj[part_value] = {}
            current_obj = current_obj[part_value]
        elif part_type == 'index':
            current_obj = current_obj[part_value]
    
    # Apply the final operation
    last_type, last_value = parts[-1]
    
    if value == "__DELETE__":
        if last_type == 'index':
            # Delete from array
            del current_obj[last_value]
        elif last_type == 'field':
            # Delete field
            if last_value in current_obj:
                del current_obj[last_value]
    else:
        if last_type == 'index':
            # Update array element
            # CRITICAL: Verify index exists, do NOT create new elements
            if isinstance(current_obj, list):
                if last_value < 0 or last_value >= len(current_obj):
                    print(f"⚠ Skipping patch for non-existent index {last_value} (array has {len(current_obj)} elements)")
                    return
            current_obj[last_value] = value
        elif last_type == 'field':
            # Update field
            current_obj[last_value] = value

